export type Q={id:string,text:string,options:string[],answer:number,topic:string,explanation:string};
export const topics=['Force & motion','Contact forces','Pressure & area','Fluid pressure'];
const rows:[string,string[],number,string][]=[
['A stationary ball moves when kicked. What changed?',['A force acted on it','Its mass vanished','Gravity disappeared','Its material changed'],0,'A force can change the state of motion.'],
['Two equal pushes act on a box in opposite directions. What is the net force?',['Double the push','Zero','Only the left push','Only the right push'],1,'Equal opposing forces cancel.'],
['A sideways kick turns a moving ball. What did the force change?',['Its mass','Its colour','Its direction','Its material'],2,'Force can change direction as well as speed.'],
['A rolling ball slows on grass. Why?',['It loses mass','Friction opposes motion','Air adds speed','Gravity disappears'],1,'Friction opposes relative motion.'],
['Why do shoe soles have grooves?',['To remove gravity','To add height','To improve grip','To reduce mass'],2,'Grooves improve traction.'],
['Which force requires contact?',['Gravity','Magnetic attraction','Electrostatic attraction','Friction'],3,'Friction acts between surfaces in contact.'],
['Why are wide school-bag straps more comfortable?',['They spread force over more area','They remove weight','They increase pressure','They change gravity'],0,'More area means less pressure for the same force.'],
['A sharp knife cuts better with the same force because it has…',['More heat','Less contact area','Less gravity','More mass'],1,'Smaller area creates greater pressure.'],
['Why do broad tractor tyres help on soft soil?',['They remove weight','They increase pressure','They spread weight over more area','They remove friction'],2,'Greater area reduces pressure on the soil.'],
['Water escapes faster from a lower hole in a bottle. Why?',['Pressure increases with depth','Water below is lighter','The hole creates gravity','Pressure is always equal'],0,'A deeper point has more water above it.'],
['Why is a dam thicker at its base?',['Water is warmer','Water pressure is greater deeper down','It needs less material','Air pressure is zero'],1,'Greater water pressure at depth requires stronger support.'],
['A balloon expands in every direction. What does this suggest?',['Air has no force','Pressure acts only down','Air pressure acts in all directions','Rubber creates air'],2,'Gas pressure acts on all inner surfaces.']];
export const bank:Q[]=rows.map((r,i)=>({id:'q'+i,text:r[0],options:r[1],answer:r[2],topic:topics[Math.floor(i/3)],explanation:r[3]}));
const names=['Aarav','Ananya','Vihaan','Diya','Arjun','Ishita','Aditya','Meera','Rohan','Saanvi','Kabir','Aisha','Reyansh','Kavya','Ishaan','Nitya','Dev','Tara','Krish','Myra','Vivaan','Avni','Aryan','Siya','Dhruv'];
const surnames=['Sharma','Patel','Verma','Singh','Rao','Das','Gupta','Joshi','Kumar','Nair'];
export const students=Array.from({length:50},(_,i)=>({id:'STU-'+String(i+1).padStart(3,'0'),name:names[i%25]+' '+surnames[(i*3+Math.floor(i/25))%10],roll:i+1}));
export type Submission={studentId:string,answers:(number|null)[]};
export function sample(cls='8A',old=false):Submission[]{return students.slice(0,cls==='8A'?47:46).map((s,i)=>({studentId:s.id,answers:bank.map((q,j)=>((i*17+j*23+(cls==='8B'?13:0))%100)<(old?[68,63,30,52]:[86,77,43,68])[Math.floor(j/3)]?q.answer:(q.answer+1+i%2)%4)}))}
export function analyse(subs:Submission[],threshold=50,questions=bank){const ts=[...new Set(questions.map(q=>q.topic))];const results=subs.map(s=>{const scores=Object.fromEntries(ts.map(t=>{const ix=questions.map((q,i)=>q.topic===t?i:-1).filter(i=>i>=0);return[t,Math.round(100*ix.filter(i=>s.answers[i]===questions[i].answer).length/ix.length)]}));const correct=questions.filter((q,j)=>q.answer===s.answers[j]).length;return{...s,...students.find(x=>x.id===s.studentId),scores,score:Math.round(100*correct/questions.length)}});const concepts=ts.map(topic=>{const affected=results.filter(s=>s.scores[topic]<threshold),percentage=results.length?Math.round(100*affected.length/results.length):0;return{topic,affected,percentage,success:results.length?Math.round(results.reduce((n,s)=>n+s.scores[topic],0)/results.length):0,action:affected.length===0?'No additional support':percentage>=50?'Whole-class revisit':affected.length<=4?'30-minute small group':'Targeted practice'}});return{results,concepts,average:results.length?Math.round(results.reduce((n,s)=>n+s.score,0)/results.length):0,highest:results.length?Math.max(...results.map(s=>s.score)):0,lowest:results.length?Math.min(...results.map(s=>s.score)):0}}
export function draft(name:string,score:number,weak:string[]){return name.split(' ')[0]+(score>=80?' is doing very well and demonstrates a strong understanding of this chapter. ':score>=50?' is developing well and understands many ideas in this chapter. ':' is building their understanding of this chapter. ')+(weak.length?'A little extra encouragement with '+weak.join(' and ').toLowerCase()+' would help. You can support them by discussing an everyday example together and asking them to explain their thinking.':'Keep encouraging them to explain everyday examples in their own words.')}

